# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{git-fogbugz}
  s.version = "0.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Roy W. Black"]
  s.date = %q{2009-11-21}
  s.default_executable = %q{git-fogbugz}
  s.description = %q{Git integretion with a FogBugz server}
  s.email = %q{roy@roywblack.com}
  s.executables = ["git-fogbugz"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/git-fogbugz",
     "git-fogbugz.gemspec",
     "lib/git_fogbugz.rb",
     "test/helper.rb",
     "test/test_git-fogbugz.rb"
  ]
  s.homepage = %q{http://github.com/roywblack/git-fogbugz}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Log git pushes to fogbugz}
  s.test_files = [
    "test/helper.rb",
     "test/test_git-fogbugz.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<grit>, [">= 2.0.0"])
    else
      s.add_dependency(%q<grit>, [">= 2.0.0"])
    end
  else
    s.add_dependency(%q<grit>, [">= 2.0.0"])
  end
end

